# Docker Compose configuration for Profile Automation System

services:
  profile-automation:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app.db:/app/app.db
      - ./.env:/app/.env
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - DEBUG=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
